### ISSUE TITLE
Argument for choosing python with django

### ISSUE THREAD

**Issue by dprzygocka** [szymongalecki/ITU-MiniTwit#28]
MSc students
OBS MSc students: Remember to log and provide good arguments for the choice of programming language and framework. Likely, a feature mapping/comparison or a mini-benchmark is a good choice.

**Comment by szymongalecki** [comment]
I don't think we discussed it a lot.

Does anyone have any insight that you would like to include?

I would cover:
- everyone in our team knows Python, so everyone can read/code review
- fast development time
- FastAPI performance is supposed to be comparable with Go's
