### ISSUE TITLE
favicon issue

### ISSUE THREAD

**Issue by dprzygocka** [szymongalecki/ITU-MiniTwit#32]

**Comment by szymongalecki** [comment]
What is favicon issue?

**Comment by dprzygocka** [comment]
![image](https://user-images.githubusercontent.com/58267360/223156312-c601b8cb-3da6-41d4-8448-a98d0104c661.png)

**Comment by dprzygocka** [comment]
this is favicon issue

**Comment by szymongalecki** [comment]
Is this an error from minitwit application when it used an API database?

**Comment by marcusgunnebo** [comment]
> Is this an error from minitwit application when it used an API database?

It is because we don't have an favicon and the applications then looks for a user named "favicon.ico". I could take a look at it?
